### PR TITLE
Rebuild for Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #1

### CODE REVIEW

**Comment by bryanwweber** [comment]
It seems the Python 3.7 failures are due to not being able to use Cython in the build from the sdist. I've opened an issue over at the CoolProp repo to report this failure: https://github.com/CoolProp/CoolProp/issues/1777

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge/coolprop This is ready to review/merge.

**Comment by danilomendesdias** [comment]
Thank you, @xhochy.

**Comment by bryanwweber** [comment]
@danilomendesdias @xhochy The build here is not being done for Python 3.7. Was that the intention?

**Comment by xhochy** [comment]
@bryanwweber Yes, the package is not built for 3.7. Upstream needs to update the C-files that were generated by Cython for Python 3.7 support.

**Comment by bryanwweber** [comment]
@xhochy OK, this will have to be re-rendered I suppose when upstream is fixed. I think they'll have to release a new version to upload the sdist to PyPI so it can probably take place as part of that process.

**Pull request merged**
